import Header from "../../components/body/Header";
export const metadata = {
  title: "search",
  description: "Generated by create next app",
};

export default function searchLayout({ children }) {
  return <>{children}</>;
}
