import "../styles/globals.css";
import Header from "../components/body/Header";
export const metadata = {
  title: "Image Saerch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh">
      <body className="bg-gray-800">
        <Header />
        {/* 根據 showHeader 控制是否顯示 Header */}
        {children}
      </body>
    </html>
  );
}
